environment                = "prod"
aws_region                 = "us-east-1"
alb_certificate_arn        = "arn:aws:acm:us-east-1:123456789012:certificate/example-prod"
vpc_az_count               = 3
vpc_nat_gateway_per_az     = true
enable_rds_secret_rotation = true
rds_secret_rotation_days   = 30
rds_allocated_storage       = 100
rds_max_allocated_storage   = 1000
rds_performance_insights_enabled = true
enable_cost_budget          = true
cost_budget_amount          = 800
cost_budget_threshold_percent = 70
cost_budget_emails          = ["finops@example.com", "cloud@example.com"]
enable_waf                  = true
waf_rate_limit              = 2500
